-- Rename INVOICED status to VETTED in JobStatus enum
ALTER TYPE "JobStatus" RENAME VALUE 'INVOICED' TO 'VETTED';

-- Rename INVOICE_OFFICER role to VETTING_OFFICER in UserRole enum
ALTER TYPE "UserRole" RENAME VALUE 'INVOICE_OFFICER' TO 'VETTING_OFFICER';

